"""
Pending post model for moderation queue.

Stores draft posts/comments awaiting human review before publishing to Reddit.
"""

from sqlalchemy import Column, String, Text, ForeignKey, Index
from sqlalchemy.orm import relationship
import json

from app.models.base import Base, UUIDMixin, TimestampMixin, ModelMixin


class PendingPost(Base, UUIDMixin, TimestampMixin, ModelMixin):
    """
    Pending post in moderation queue.

    Draft posts/comments generated by the agent that await human review
    and approval before being published to Reddit. Supports auto-posting
    bypass when auto_posting_enabled is True.

    Attributes:
        id: UUID primary key
        persona_id: Foreign key to Persona
        content: The draft content to be posted
        post_type: Type of post (comment, reply, post)
        target_subreddit: Subreddit where post will be published
        parent_id: Parent item ID if this is a reply
        draft_metadata: JSON metadata (context, reasoning, confidence)
        status: Moderation status (pending, approved, rejected)
        reviewed_by: Username/ID of reviewer
        reviewed_at: Timestamp when reviewed
        created_at: When draft was created
        updated_at: When draft was last modified
    """

    __tablename__ = "pending_posts"

    persona_id = Column(
        String,
        ForeignKey("personas.id", ondelete="CASCADE"),
        nullable=False,
        doc="Foreign key to Persona"
    )

    content = Column(
        Text,
        nullable=False,
        doc="The draft content to be posted"
    )

    post_type = Column(
        String(50),
        nullable=True,
        doc="Type of post (comment, reply, post)"
    )

    target_subreddit = Column(
        String(255),
        nullable=True,
        doc="Subreddit where post will be published"
    )

    parent_id = Column(
        String(255),
        nullable=True,
        doc="Parent item ID if this is a reply"
    )

    draft_metadata = Column(
        Text,
        nullable=True,
        doc="JSON metadata (context, reasoning, confidence)"
    )

    status = Column(
        String(50),
        default="pending",
        doc="Moderation status (pending, approved, rejected)"
    )

    reviewed_by = Column(
        String(255),
        nullable=True,
        doc="Username/ID of reviewer"
    )

    reviewed_at = Column(
        String,
        nullable=True,
        doc="Timestamp when reviewed"
    )

    # Relationships
    persona = relationship("Persona", back_populates="pending_posts")

    # Indexes
    __table_args__ = (
        Index("idx_pending_posts_status", "status"),
        Index("idx_pending_posts_created", "created_at"),
        Index("idx_pending_posts_persona", "persona_id"),
        Index("idx_pending_posts_subreddit", "target_subreddit"),
    )

    def get_draft_metadata(self) -> dict:
        """
        Parse draft_metadata JSON to dictionary.

        Returns:
            Dictionary with draft metadata
        """
        if not self.draft_metadata:
            return {}
        try:
            return json.loads(self.draft_metadata)
        except json.JSONDecodeError:
            return {}

    def set_draft_metadata(self, metadata_dict: dict) -> None:
        """
        Set draft_metadata from dictionary.

        Args:
            metadata_dict: Metadata dictionary to store
        """
        self.draft_metadata = json.dumps(metadata_dict)

    def approve(self, reviewer: str) -> None:
        """
        Approve the pending post.

        Args:
            reviewer: Username/ID of the reviewer
        """
        from datetime import datetime
        self.status = "approved"
        self.reviewed_by = reviewer
        self.reviewed_at = datetime.utcnow().isoformat()

    def reject(self, reviewer: str) -> None:
        """
        Reject the pending post.

        Args:
            reviewer: Username/ID of the reviewer
        """
        from datetime import datetime
        self.status = "rejected"
        self.reviewed_by = reviewer
        self.reviewed_at = datetime.utcnow().isoformat()

    def __repr__(self) -> str:
        return (
            f"PendingPost(id='{self.id}', "
            f"status='{self.status}', "
            f"type='{self.post_type}')"
        )
